# Generated by Django 5.0 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_booking_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='lawyer_id',
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
